version: '3'

services:
  fast_api:
    build: .
    container_name: fast_api
    environment:
      ENV_FILE: .env.example
    ports:
      - 8888:8000

  postgres:
    image: postgres:14
    container_name: postgres_test
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5555:5432

  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: elasticsearch_test
    environment:
      cluster.name: docker-cluster
      network.host: 0.0.0.0
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.monitoring.collection.enabled: true
      indices.query.bool.max_clause_count: 100000
      ES_JAVA_OPTS: -Xmx4096m -Xms1024m
    ports:
      - 9292:9200
