version: '3'

services:
  fastapi_demo:
    image: umbreella/searchus_test_task:latest
    container_name: fastapi_demo
    environment:
      ENV_FILE: demo/.env.example
    ports:
      - 8000:8000

  postgres:
    image: postgres:14
    container_name: postgres_test
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  elasticsearch:
    image: elasticsearch:8.8.0
    container_name: elasticsearch_test
    environment:
      cluster.name: docker-cluster
      network.host: 0.0.0.0
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.monitoring.collection.enabled: true
      indices.query.bool.max_clause_count: 100000
      ES_JAVA_OPTS: -Xmx4096m -Xms1024m
